
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: rentacar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    image: omerriza/rentacar         #omerriza/rentacar-backend  #dockerhubtaki "docker pull omerriza/rentacar-backend:latest"   -> bundan bunu->omerriza/rentacar-backend alıp image a koy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rentacar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - /Users/macbook/Documents/GitHub/rentacar/uploads:/app/uploads
      - /Users/macbook/Documents:/Users/macbook/Documents

volumes:
  postgres_data: